[Style]
WindowPadding = [ 4, 4 ]
WindowRounding = 0
WindowBorderSize = 1
WindowTitleAlign = [ 0.5, 0.5 ]
ChildRounding = 0
FramePadding = [ 4, 4 ]
FrameRounding = 0
FrameBorderSize = 1
ItemSpacing = [ 4, 4 ]
ScrollbarRounding = 0
GrabRounding = 0
TabRounding = 0

[Colors]
Text = "{text_color}"
TextDisabled = "{dark_border_color}"
WindowBg = "{background_color}"
ChildBg = "{dark_background_color}"
PopupBg = "{background_color}"
Border = "{light_border_color}"
BorderShadow = "{dark_border_color}"
FrameBg = "{average_border_color}"
FrameBgHovered = "{average_border_color}"
FrameBgActive = "{average_border_color}"
TitleBg = "{title_background_color}"
TitleBgActive = "{title_background_color}"
TitleBgCollapsed = "{title_background_color}"
MenuBarBg = "{dark_background_color}"
ScrollbarBg = "{average_border_color}"
ScrollbarGrab = "{background_color}"
ScrollbarGrabHovered = "{background_color}"
ScrollbarGrabActive = "{light_border_color}"
CheckMark = "{text_color}"
SliderGrab = "{background_color}"
SliderGrabActive = "{light_border_color}"
Button = "{background_color}"
ButtonHovered = "{background_color}"
ButtonActive = "{light_border_color}"
Header = "{background_color}"
HeaderHovered = "{dark_background_color}"
HeaderActive = "{background_color}"
Separator = "{dark_border_color}"
SeparatorHovered = "{dark_border_color}"
SeparatorActive = "{dark_border_color}"
ResizeGrip = "{dark_border_color}"
ResizeGripHovered = "{dark_border_color}"
ResizeGripActive = "{dark_border_color}"
Tab = "{dark_background_color}"
TabHovered = "{dark_background_color}"
TabActive = "{background_color}"
TabUnfocused = "{dark_background_color}"
TabUnfocusedActive = "{background_color}"
PlotLines = "{plot_color}"
PlotLinesHovered = "{plot_color}"
PlotHistogram = "{plot_color}"
PlotHistogramHovered = "{plot_color}"
TableHeaderBg = "{dark_background_color}"
TableBorderStrong = "{dark_border_color}"
TableBorderLight = "{transparent}"
TableRowBg = "{background_color}"
TableRowBgAlt = "{average_background_border_color}"
TextSelectedBg = "{dark_border_color}"
DragDropTarget = "{dark_border_color}"
NavHighlight = "{dark_border_color}"
