[Style]
WindowPadding = [ 4, 4 ]
WindowRounding = 0
WindowBorderSize = 1
WindowTitleAlign = [ 0.5, 0.5 ]
ChildRounding = 0
FramePadding = [ 4, 4 ]
FrameRounding = 0
FrameBorderSize = 1
ItemSpacing = [ 4, 4 ]
ScrollbarRounding = 0
GrabRounding = 0
TabRounding = 0

[Colors]
Text = "#FFBFBF"
TextDisabled = "#8F2727"
WindowBg = "#B34F4F"
ChildBg = "#A33B3B"
PopupBg = "#B34F4F"
Border = "#C76767"
BorderShadow = "#8F2727"
FrameBg = "#AB4747"
FrameBgHovered = "#AB4747"
FrameBgActive = "#AB4747"
TitleBg = "#2F4343"
TitleBgActive = "#2F4343"
TitleBgCollapsed = "#2F4343"
MenuBarBg = "#A33B3B"
ScrollbarBg = "#AB4747"
ScrollbarGrab = "#B34F4F"
ScrollbarGrabHovered = "#B34F4F"
ScrollbarGrabActive = "#C76767"
CheckMark = "#FFBFBF"
SliderGrab = "#B34F4F"
SliderGrabActive = "#C76767"
Button = "#B34F4F"
ButtonHovered = "#B34F4F"
ButtonActive = "#C76767"
Header = "#B34F4F"
HeaderHovered = "#A33B3B"
HeaderActive = "#B34F4F"
Separator = "#8F2727"
SeparatorHovered = "#8F2727"
SeparatorActive = "#8F2727"
ResizeGrip = "#8F2727"
ResizeGripHovered = "#8F2727"
ResizeGripActive = "#8F2727"
Tab = "#A33B3B"
TabHovered = "#A33B3B"
TabActive = "#B34F4F"
TabUnfocused = "#A33B3B"
TabUnfocusedActive = "#B34F4F"
PlotLines = "#EFF3F3"
PlotLinesHovered = "#EFF3F3"
PlotHistogram = "#EFF3F3"
PlotHistogramHovered = "#EFF3F3"
TableHeaderBg = "#A33B3B"
TableBorderStrong = "#8F2727"
TableBorderLight = "#00000000"
TableRowBg = "#B34F4F"
TableRowBgAlt = "#BD5B5B"
TextSelectedBg = "#8F2727"
DragDropTarget = "#8F2727"
NavHighlight = "#8F2727"
