[Style]
WindowPadding = [ 4, 4 ]
WindowRounding = 0
WindowBorderSize = 1
WindowTitleAlign = [ 0.5, 0.5 ]
ChildRounding = 0
FramePadding = [ 4, 4 ]
FrameRounding = 0
FrameBorderSize = 1
ItemSpacing = [ 4, 4 ]
ScrollbarRounding = 0
GrabRounding = 0
TabRounding = 0

[Colors]
Text = "#CFF3DF"
TextDisabled = "#3B734B"
WindowBg = "#639B77"
ChildBg = "#4F875F"
PopupBg = "#639B77"
Border = "#93C7A7"
BorderShadow = "#3B734B"
FrameBg = "#679D79"
FrameBgHovered = "#679D79"
FrameBgActive = "#679D79"
TitleBg = "#2F4343"
TitleBgActive = "#2F4343"
TitleBgCollapsed = "#2F4343"
MenuBarBg = "#4F875F"
ScrollbarBg = "#679D79"
ScrollbarGrab = "#639B77"
ScrollbarGrabHovered = "#639B77"
ScrollbarGrabActive = "#93C7A7"
CheckMark = "#CFF3DF"
SliderGrab = "#639B77"
SliderGrabActive = "#93C7A7"
Button = "#639B77"
ButtonHovered = "#639B77"
ButtonActive = "#93C7A7"
Header = "#639B77"
HeaderHovered = "#4F875F"
HeaderActive = "#639B77"
Separator = "#3B734B"
SeparatorHovered = "#3B734B"
SeparatorActive = "#3B734B"
ResizeGrip = "#3B734B"
ResizeGripHovered = "#3B734B"
ResizeGripActive = "#3B734B"
Tab = "#4F875F"
TabHovered = "#4F875F"
TabActive = "#639B77"
TabUnfocused = "#4F875F"
TabUnfocusedActive = "#639B77"
PlotLines = "#EFF3F3"
PlotLinesHovered = "#EFF3F3"
PlotHistogram = "#EFF3F3"
PlotHistogramHovered = "#EFF3F3"
TableHeaderBg = "#4F875F"
TableBorderStrong = "#3B734B"
TableBorderLight = "#00000000"
TableRowBg = "#639B77"
TableRowBgAlt = "#7BB18F"
TextSelectedBg = "#3B734B"
DragDropTarget = "#3B734B"
NavHighlight = "#3B734B"
