[Style]
WindowPadding = [ 4, 4 ]
WindowRounding = 0
WindowBorderSize = 1
WindowTitleAlign = [ 0.5, 0.5 ]
ChildRounding = 0
FramePadding = [ 4, 4 ]
FrameRounding = 0
FrameBorderSize = 1
ItemSpacing = [ 4, 4 ]
ScrollbarRounding = 0
GrabRounding = 0
TabRounding = 0

[Colors]
Text = "#E7DBC3"
TextDisabled = "#5B3F1F"
WindowBg = "#8F7F6B"
ChildBg = "#7B674B"
PopupBg = "#8F7F6B"
Border = "#A3937F"
BorderShadow = "#5B3F1F"
FrameBg = "#7F694F"
FrameBgHovered = "#7F694F"
FrameBgActive = "#7F694F"
TitleBg = "#2F4343"
TitleBgActive = "#2F4343"
TitleBgCollapsed = "#2F4343"
MenuBarBg = "#7B674B"
ScrollbarBg = "#7F694F"
ScrollbarGrab = "#8F7F6B"
ScrollbarGrabHovered = "#8F7F6B"
ScrollbarGrabActive = "#A3937F"
CheckMark = "#E7DBC3"
SliderGrab = "#8F7F6B"
SliderGrabActive = "#A3937F"
Button = "#8F7F6B"
ButtonHovered = "#8F7F6B"
ButtonActive = "#A3937F"
Header = "#8F7F6B"
HeaderHovered = "#7B674B"
HeaderActive = "#8F7F6B"
Separator = "#5B3F1F"
SeparatorHovered = "#5B3F1F"
SeparatorActive = "#5B3F1F"
ResizeGrip = "#5B3F1F"
ResizeGripHovered = "#5B3F1F"
ResizeGripActive = "#5B3F1F"
Tab = "#7B674B"
TabHovered = "#7B674B"
TabActive = "#8F7F6B"
TabUnfocused = "#7B674B"
TabUnfocusedActive = "#8F7F6B"
PlotLines = "#EFF3F3"
PlotLinesHovered = "#EFF3F3"
PlotHistogram = "#EFF3F3"
PlotHistogramHovered = "#EFF3F3"
TableHeaderBg = "#7B674B"
TableBorderStrong = "#5B3F1F"
TableBorderLight = "#00000000"
TableRowBg = "#8F7F6B"
TableRowBgAlt = "#998975"
TextSelectedBg = "#5B3F1F"
DragDropTarget = "#5B3F1F"
NavHighlight = "#5B3F1F"
