[Style]
WindowPadding = [ 4, 4 ]
WindowRounding = 0
WindowBorderSize = 1
WindowTitleAlign = [ 0.5, 0.5 ]
ChildRounding = 0
FramePadding = [ 4, 4 ]
FrameRounding = 0
FrameBorderSize = 1
ItemSpacing = [ 4, 4 ]
ScrollbarRounding = 0
GrabRounding = 0
TabRounding = 0

[Colors]
Text = "#F3CB1B"
TextDisabled = "#773F00"
WindowBg = "#A76F07"
ChildBg = "#8F5307"
PopupBg = "#A76F07"
Border = "#BF8B0F"
BorderShadow = "#773F00"
FrameBg = "#9B6507"
FrameBgHovered = "#9B6507"
FrameBgActive = "#9B6507"
TitleBg = "#2F4343"
TitleBgActive = "#2F4343"
TitleBgCollapsed = "#2F4343"
MenuBarBg = "#8F5307"
ScrollbarBg = "#9B6507"
ScrollbarGrab = "#A76F07"
ScrollbarGrabHovered = "#A76F07"
ScrollbarGrabActive = "#BF8B0F"
CheckMark = "#F3CB1B"
SliderGrab = "#A76F07"
SliderGrabActive = "#BF8B0F"
Button = "#A76F07"
ButtonHovered = "#A76F07"
ButtonActive = "#BF8B0F"
Header = "#A76F07"
HeaderHovered = "#8F5307"
HeaderActive = "#A76F07"
Separator = "#773F00"
SeparatorHovered = "#773F00"
SeparatorActive = "#773F00"
ResizeGrip = "#773F00"
ResizeGripHovered = "#773F00"
ResizeGripActive = "#773F00"
Tab = "#8F5307"
TabHovered = "#8F5307"
TabActive = "#A76F07"
TabUnfocused = "#8F5307"
TabUnfocusedActive = "#A76F07"
PlotLines = "#EFF3F3"
PlotLinesHovered = "#EFF3F3"
PlotHistogram = "#EFF3F3"
PlotHistogramHovered = "#EFF3F3"
TableHeaderBg = "#8F5307"
TableBorderStrong = "#773F00"
TableBorderLight = "#00000000"
TableRowBg = "#A76F07"
TableRowBgAlt = "#B37D0B"
TextSelectedBg = "#773F00"
DragDropTarget = "#773F00"
NavHighlight = "#773F00"
