[Style]
WindowPadding = [ 4, 4 ]
WindowRounding = 0
WindowBorderSize = 1
WindowTitleAlign = [ 0.5, 0.5 ]
ChildRounding = 0
FramePadding = [ 4, 4 ]
FrameRounding = 0
FrameBorderSize = 1
ItemSpacing = [ 4, 4 ]
ScrollbarRounding = 0
GrabRounding = 0
TabRounding = 0

[Colors]
Text = "#EFEFFF"
TextDisabled = "#53538B"
WindowBg = "#8B8BBF"
ChildBg = "#7777AF"
PopupBg = "#8B8BBF"
Border = "#B7B7DF"
BorderShadow = "#53538B"
FrameBg = "#8585B5"
FrameBgHovered = "#8585B5"
FrameBgActive = "#8585B5"
TitleBg = "#2F4343"
TitleBgActive = "#2F4343"
TitleBgCollapsed = "#2F4343"
MenuBarBg = "#7777AF"
ScrollbarBg = "#8585B5"
ScrollbarGrab = "#8B8BBF"
ScrollbarGrabHovered = "#8B8BBF"
ScrollbarGrabActive = "#B7B7DF"
CheckMark = "#EFEFFF"
SliderGrab = "#8B8BBF"
SliderGrabActive = "#B7B7DF"
Button = "#8B8BBF"
ButtonHovered = "#8B8BBF"
ButtonActive = "#B7B7DF"
Header = "#8B8BBF"
HeaderHovered = "#7777AF"
HeaderActive = "#8B8BBF"
Separator = "#53538B"
SeparatorHovered = "#53538B"
SeparatorActive = "#53538B"
ResizeGrip = "#53538B"
ResizeGripHovered = "#53538B"
ResizeGripActive = "#53538B"
Tab = "#7777AF"
TabHovered = "#7777AF"
TabActive = "#8B8BBF"
TabUnfocused = "#7777AF"
TabUnfocusedActive = "#8B8BBF"
PlotLines = "#EFF3F3"
PlotLinesHovered = "#EFF3F3"
PlotHistogram = "#EFF3F3"
PlotHistogramHovered = "#EFF3F3"
TableHeaderBg = "#7777AF"
TableBorderStrong = "#53538B"
TableBorderLight = "#00000000"
TableRowBg = "#8B8BBF"
TableRowBgAlt = "#A1A1CF"
TextSelectedBg = "#53538B"
DragDropTarget = "#53538B"
NavHighlight = "#53538B"
