[Style]
WindowPadding = [ 4, 4 ]
WindowRounding = 0
WindowBorderSize = 1
WindowTitleAlign = [ 0.5, 0.5 ]
ChildRounding = 0
FramePadding = [ 4, 4 ]
FrameRounding = 0
FrameBorderSize = 1
ItemSpacing = [ 4, 4 ]
ScrollbarRounding = 0
GrabRounding = 0
TabRounding = 0

[Colors]
Text = "#D7F7FF"
TextDisabled = "#2B67DF"
WindowBg = "#5BA3E7"
ChildBg = "#4387E3"
PopupBg = "#5BA3E7"
Border = "#77BBEF"
BorderShadow = "#2B67DF"
FrameBg = "#5191E7"
FrameBgHovered = "#5191E7"
FrameBgActive = "#5191E7"
TitleBg = "#2F4343"
TitleBgActive = "#2F4343"
TitleBgCollapsed = "#2F4343"
MenuBarBg = "#4387E3"
ScrollbarBg = "#5191E7"
ScrollbarGrab = "#5BA3E7"
ScrollbarGrabHovered = "#5BA3E7"
ScrollbarGrabActive = "#77BBEF"
CheckMark = "#D7F7FF"
SliderGrab = "#5BA3E7"
SliderGrabActive = "#77BBEF"
Button = "#5BA3E7"
ButtonHovered = "#5BA3E7"
ButtonActive = "#77BBEF"
Header = "#5BA3E7"
HeaderHovered = "#4387E3"
HeaderActive = "#5BA3E7"
Separator = "#2B67DF"
SeparatorHovered = "#2B67DF"
SeparatorActive = "#2B67DF"
ResizeGrip = "#2B67DF"
ResizeGripHovered = "#2B67DF"
ResizeGripActive = "#2B67DF"
Tab = "#4387E3"
TabHovered = "#4387E3"
TabActive = "#5BA3E7"
TabUnfocused = "#4387E3"
TabUnfocusedActive = "#5BA3E7"
PlotLines = "#EFF3F3"
PlotLinesHovered = "#EFF3F3"
PlotHistogram = "#EFF3F3"
PlotHistogramHovered = "#EFF3F3"
TableHeaderBg = "#4387E3"
TableBorderStrong = "#2B67DF"
TableBorderLight = "#00000000"
TableRowBg = "#5BA3E7"
TableRowBgAlt = "#69AFEB"
TextSelectedBg = "#2B67DF"
DragDropTarget = "#2B67DF"
NavHighlight = "#2B67DF"
