[Style]
WindowPadding = [ 4, 4 ]
WindowRounding = 0
WindowBorderSize = 1
WindowTitleAlign = [ 0.5, 0.5 ]
ChildRounding = 0
FramePadding = [ 4, 4 ]
FrameRounding = 0
FrameBorderSize = 1
ItemSpacing = [ 4, 4 ]
ScrollbarRounding = 0
GrabRounding = 0
TabRounding = 0

[Colors]
Text = "#DFF7BF"
TextDisabled = "#6F874F"
WindowBg = "#9FB76F"
ChildBg = "#879F5F"
PopupBg = "#9FB76F"
Border = "#B7CF7F"
BorderShadow = "#6F874F"
FrameBg = "#93AB67"
FrameBgHovered = "#93AB67"
FrameBgActive = "#93AB67"
TitleBg = "#2F4343"
TitleBgActive = "#2F4343"
TitleBgCollapsed = "#2F4343"
MenuBarBg = "#879F5F"
ScrollbarBg = "#93AB67"
ScrollbarGrab = "#9FB76F"
ScrollbarGrabHovered = "#9FB76F"
ScrollbarGrabActive = "#B7CF7F"
CheckMark = "#DFF7BF"
SliderGrab = "#9FB76F"
SliderGrabActive = "#B7CF7F"
Button = "#9FB76F"
ButtonHovered = "#9FB76F"
ButtonActive = "#B7CF7F"
Header = "#9FB76F"
HeaderHovered = "#879F5F"
HeaderActive = "#9FB76F"
Separator = "#6F874F"
SeparatorHovered = "#6F874F"
SeparatorActive = "#6F874F"
ResizeGrip = "#6F874F"
ResizeGripHovered = "#6F874F"
ResizeGripActive = "#6F874F"
Tab = "#879F5F"
TabHovered = "#879F5F"
TabActive = "#9FB76F"
TabUnfocused = "#879F5F"
TabUnfocusedActive = "#9FB76F"
PlotLines = "#EFF3F3"
PlotLinesHovered = "#EFF3F3"
PlotHistogram = "#EFF3F3"
PlotHistogramHovered = "#EFF3F3"
TableHeaderBg = "#879F5F"
TableBorderStrong = "#6F874F"
TableBorderLight = "#00000000"
TableRowBg = "#9FB76F"
TableRowBgAlt = "#ABC377"
TextSelectedBg = "#6F874F"
DragDropTarget = "#6F874F"
NavHighlight = "#6F874F"
